// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuvNUG5Ctyfstgxe9m-G2_0vfmzeYvlOM',
    appId: '1:699128640565:web:0b8028264c372053fa2d7c',
    messagingSenderId: '699128640565',
    projectId: 'shuttle-stalk',
    authDomain: 'shuttle-stalk.firebaseapp.com',
    databaseURL: 'https://shuttle-stalk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shuttle-stalk.appspot.com',
    measurementId: 'G-5JRLPYR81G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDORZbzYA-UjbN4ftcyjtbFUdAtwz3gsMM',
    appId: '1:699128640565:android:37f2c51bbde88e76fa2d7c',
    messagingSenderId: '699128640565',
    projectId: 'shuttle-stalk',
    databaseURL: 'https://shuttle-stalk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shuttle-stalk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvbrHgyvuMh4PTaPyMkinV6kVWaWRaabo',
    appId: '1:699128640565:ios:8fce8a9d43237235fa2d7c',
    messagingSenderId: '699128640565',
    projectId: 'shuttle-stalk',
    databaseURL: 'https://shuttle-stalk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shuttle-stalk.appspot.com',
    iosBundleId: 'com.example.shuttleStalkDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvbrHgyvuMh4PTaPyMkinV6kVWaWRaabo',
    appId: '1:699128640565:ios:9bcfa7f40b9a9488fa2d7c',
    messagingSenderId: '699128640565',
    projectId: 'shuttle-stalk',
    databaseURL: 'https://shuttle-stalk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shuttle-stalk.appspot.com',
    iosBundleId: 'com.example.shuttleStalkDriver.RunnerTests',
  );
}
